# Generated by Django 4.1.2 on 2022-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventmodel_delete_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmodel",
            name="image",
            field=models.ImageField(upload_to="event/images/", verbose_name="picture"),
        ),
    ]
